image: openjdk:25-jdk

stages:
  - quality
  - build
  - test

code-quality:
  stage: quality
  script:
    - ./gradlew check

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

