image: gradle:9.1.0-jdk25

stages:
  - quality
  - build
  - test

code-quality:
  stage: quality
  script:
    - ./gradlew check

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

